version: "2"

services:
  audio:
    restart: always
    image: balenablocks/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    networks:
      - audio

  fluidsynth:
    restart: always
    build:
      context: .
      dockerfile: fluidsynth.Dockerfile
    environment:
      PULSE_SERVER: audio:4317
      ENABLED: "true"
    volumes:
      - soundfonts:/usr/share/soundfonts
    privileged: true
    networks:
      - audio
      - fluidsynth

  autoconnect:
    restart: always
    image: texthtml/midi-synthesizer-autoconnect
    privileged: true
    network_mode: none

  webui:
    restart: always
    image: texthtml/fluidsynth-webapp
    environment:
      FLUIDSYNTH_HOST: fluidsynth
      FLUIDSYNTH_PORT: 9988
    ports:
      - "80:7000"
    networks:
      - fluidsynth

networks:
  audio:
    driver: bridge
  fluidsynth:
    driver: bridge

volumes:
  soundfonts:
    driver: local
